/*
 * Conformance checks over the vendored yEnc encryption standards v1.2 test
 * vector fixtures (test/test-vectors/, byte-identical copies of the canonical
 * set generated by the yenc-encryption-standards repository and pinned by
 * manifest.json).
 *
 * Runs standalone via `node test/test_conformance_vectors.js` and also under
 * mocha (registered via describe/it when mocha provides the globals).
 *
 * Coverage at this stage: fixture integrity (manifest sha256 sync via node
 * crypto), VEC-05 malformed-input rejection shapes, VEC-06 NZB meta tag
 * expectations, and VEC-07 segmentIndex allocation skip rules. Cryptographic
 * round-trip vectors are exercised when Nyuu gains encrypt capability.
 *
 * Self-containment: reads only files inside nyuu/'s own tree.
 */

"use strict";

var assert = require("assert");
var fs = require("fs");
var path = require("path");
var crypto = require("crypto");

var VECTOR_FILES = [
    "argon2id.json",
    "body_encryption.json",
    "control_line_encryption.json",
    "index_allocation.json",
    "malformed_inputs.json",
    "nonce_tweak.json",
    "nzb_segment_identity.json"
];

var VECTORS_DIR = path.join(__dirname, "test-vectors");

function loadFixture(name) {
    return JSON.parse(fs.readFileSync(path.join(VECTORS_DIR, name), "utf8"));
}

function sha256(file) {
    return crypto.createHash("sha256")
        .update(fs.readFileSync(path.join(VECTORS_DIR, file)))
        .digest("hex");
}

function testManifestSha256Sync() {
    var manifest = loadFixture("manifest.json");
    assert.strictEqual(manifest.standard_version, "1.2", "fixture set must be v1.2");
    assert.deepStrictEqual(
        Object.keys(manifest.files).sort(),
        VECTOR_FILES.slice().sort(),
        "manifest must list exactly the canonical 7 vector files"
    );
    VECTOR_FILES.forEach(function(file) {
        var expected = manifest.files[file].sha256;
        assert.ok(expected, "manifest entry missing sha256 for " + file);
        assert.strictEqual(sha256(file), expected, "sha256 drift for " + file);
    });
}

function testMalformedRejectionShapes() {
    var vectors = loadFixture("malformed_inputs.json").vectors;
    assert.strictEqual(vectors.length, 46, "v1.2 malformed set has 46 vectors");

    vectors.forEach(function(v) {
        assert.ok(v.expected_error, v.id + ": expected_error");
        assert.ok(
            v.expected_rejection_stage === "PROVIDER_FAILOVER" ||
            v.expected_rejection_stage === "METADATA_VALIDATION",
            v.id + ": unexpected rejection stage " + v.expected_rejection_stage
        );
        assert.strictEqual(v.zero_output_required, true, v.id + ": zero-output guarantee");
    });

    // Authentication failures must stay retryable: eligible for provider
    // failover and never released as final output.
    var authFailures = vectors.filter(function(v) { return v.expected_error === "AUTHENTICATION_FAILURE"; });
    assert.strictEqual(authFailures.length, 4, "4 auth-failure vectors");
    authFailures.forEach(function(v) {
        assert.strictEqual(v.expected_rejection_stage, "PROVIDER_FAILOVER", v.id);
        assert.strictEqual(v.provider_failover_permitted, true, v.id);
    });

    // Metadata-shape failures are job-level, never provider corruption.
    var metadataFailures = vectors.filter(function(v) { return v.expected_rejection_stage === "METADATA_VALIDATION"; });
    assert.strictEqual(metadataFailures.length, 4, "4 metadata-validation vectors");
    metadataFailures.forEach(function(v) {
        assert.strictEqual(v.provider_failover_permitted, false, v.id);
    });

    // header_syntax vectors carry a full =yencryption line to reject; the
    // invalid whitespace is the very thing they assert.
    vectors.filter(function(v) { return v.category === "header_syntax"; }).forEach(function(v) {
        var line = v.input_line || "";
        assert.ok(
            line.indexOf("=yencryption") === 0 &&
            line.length > "=yencryption".length &&
            !/[a-zA-Z0-9]/.test(line.charAt("=yencryption".length)),
            v.id + ": header_syntax vector missing input_line"
        );
    });

    // FORBIDDEN_SEGMENT_INDEX_BYTE control-syntax vectors: bootstrap line is
    // 22 bytes with the segmentIndex in the 4 big-endian bytes at offset 16.
    vectors.filter(function(v) { return v.expected_error === "FORBIDDEN_SEGMENT_INDEX_BYTE"; }).forEach(function(v) {
        assert.ok(v.line1_hex, v.id + ": line1_hex");
        var line1 = Buffer.from(v.line1_hex, "hex");
        assert.strictEqual(line1.length, 22, v.id + ": bootstrap line must be 22 bytes");
        var index = line1.readUInt32BE(16);
        assert.ok(indexForbidden(index), v.id + ": index " + index + " should be forbidden");
    });
}

function testNzbMetaTagExpectations() {
    var vectors = loadFixture("nzb_segment_identity.json").vectors;
    assert.strictEqual(vectors.length, 33, "VEC-06 set has 33 vectors");

    var encrypted = vectors.filter(function(v) { return v.is_encrypted; });
    var unencrypted = vectors.filter(function(v) { return v.is_encrypted === false; });
    assert.ok(encrypted.length > 0, "fixture contains encrypted vectors");
    assert.strictEqual(unencrypted.length, 2, "two unencrypted reference vectors");

    encrypted.forEach(function(v) {
        assert.ok(v.nzb_xml.indexOf('<meta type="yenc_encrypted">true</meta>') !== -1, v.id);
        assert.ok(v.nzb_xml.indexOf('<meta type="password">') !== -1, v.id);
    });

    unencrypted.forEach(function(v) {
        assert.ok(v.nzb_xml.indexOf('<meta type="yenc_encrypted">') === -1, v.id);
        assert.ok(v.nzb_xml.indexOf('<meta type="password">') === -1, v.id);
        assert.strictEqual(v.expected_valid, true, v.id);
        v.expected_segments.forEach(function(segment) {
            assert.strictEqual(segment.segment_index, null, v.id);
        });
    });
}

// VEC-07: a candidate segmentIndex whose uint32 big-endian encoding contains
// 0x0A or 0x0D is forbidden; the uploader must skip forward to the next
// permitted index.
function indexForbidden(index) {
    var be = Buffer.alloc(4);
    be.writeUInt32BE(index >>> 0, 0);
    return be.includes(0x0a) || be.includes(0x0d);
}

function nextPermitted(candidate) {
    var i = candidate >>> 0;
    while (indexForbidden(i)) {
        i = (i + 1) >>> 0;
    }
    return i;
}

function testIndexAllocationSkipRules() {
    var vectors = loadFixture("index_allocation.json").vectors;
    assert.strictEqual(vectors.length, 4, "canonical VEC-07 set has 4 vectors");

    vectors.forEach(function(v) {
        var assigned = v.expected_assigned_index;
        // By design (vector 04): candidate 269 is itself forbidden - the
        // uploader must never assign it - so only the assigned index is
        // required to be permitted.
        assert.ok(!indexForbidden(assigned), v.id + ": assigned index must be permitted");
        assert.strictEqual(nextPermitted(v.candidate_index), assigned, v.id);
        var be = Buffer.alloc(4);
        be.writeUInt32BE(assigned >>> 0, 0);
        assert.strictEqual(be.toString("hex"), v.expected_index_hex, v.id);
    });
}

function testIndexAllocationReferenceSequence() {
    var vectors = loadFixture("index_allocation.json").vectors;
    var byId = {};
    vectors.forEach(function(v) { byId[v.id] = v; });
    assert.strictEqual(byId["index-allocation-01-skip-10"].expected_assigned_index, 11);
    assert.strictEqual(byId["index-allocation-02-skip-13"].expected_assigned_index, 14);
    assert.strictEqual(byId["index-allocation-03-skip-266"].expected_assigned_index, 267);
    assert.strictEqual(byId["index-allocation-04-skip-269"].expected_assigned_index, 270);
}

// Exported for the standalone runner below.
var TESTS = [
    testManifestSha256Sync,
    testMalformedRejectionShapes,
    testNzbMetaTagExpectations,
    testIndexAllocationSkipRules,
    testIndexAllocationReferenceSequence
];

// Mocha registration (mocha injects describe/it as globals).
if (typeof global.describe === "function" && typeof global.it === "function") {
    describe("yEnc encryption standards v1.2 conformance fixtures", function() {
        it("vendors all 7 vector files byte-identical to manifest.json sha256", testManifestSha256Sync);
        it("VEC-05 malformed inputs pin error class, rejection stage and zero-output", testMalformedRejectionShapes);
        it("VEC-06 encrypted NZBs carry yenc_encrypted + password meta, plain NZBs do not", testNzbMetaTagExpectations);
        it("VEC-07 segmentIndex allocation skips 0x0A/0x0D candidates", testIndexAllocationSkipRules);
        it("VEC-07 canonical skip examples keep stable expected assignments", testIndexAllocationReferenceSequence);
    });
}

// Standalone runner: `node test/test_conformance_vectors.js`.
if (require.main === module) {
    var failures = 0;
    TESTS.forEach(function(t) {
        try {
            t();
            console.log("ok - " + t.name);
        } catch (err) {
            failures++;
            console.error("not ok - " + t.name + ": " + (err && err.message ? err.message : err));
        }
    });
    if (failures) {
        process.exit(1);
    }
    console.log("conformance vectors: all " + TESTS.length + " tests passed");
}
