/*
 * Conformance checks over the vendored yEnc encryption standards v1.2 test
 * vector fixtures (test/test-vectors/, byte-identical copies of the canonical
 * set generated by the reference standards repository and pinned by
 * manifest.json). Fixture-driven via node crypto + assert + nyuu/lib/encryption.
 *
 * Runs standalone via `node test/test_conformance_vectors.js` and also under
 * mocha (registered via describe/it when mocha provides the globals).
 *
 * Covers:
 * - Fixture integrity: manifest sha256 sync via node crypto
 * - VEC-01: Argon2id key derivation against encryption.deriveMasterKey
 * - VEC-02: Nonce and tweak derivations against encryption.deriveBodyNonce,
 *           encryption.deriveControlEncKey, encryption.deriveControlTweak
 * - VEC-03: XChaCha20-Poly1305 body encryption & decryption round-trips
 *           and canonical 128-char =yencryption header building
 * - VEC-04: Radix-253 FF1 control-line encryption & decryption, Line 1
 *           bootstrap prefix, and full article multi-line passes
 * - VEC-05: Malformed input rejection shapes, error classes, and zero-output guarantee
 * - VEC-06: NZB meta tag expectations
 * - VEC-07: segmentIndex allocation skip rules and reference sequence
 *
 * Self-containment: reads only files inside nyuu/'s own tree.
 */

"use strict";

var assert = require("assert");
var fs = require("fs");
var path = require("path");
var crypto = require("crypto");
var encryption = require("../lib/encryption");

var VECTOR_FILES = [
    "argon2id.json",
    "body_encryption.json",
    "control_line_encryption.json",
    "index_allocation.json",
    "malformed_inputs.json",
    "nonce_tweak.json",
    "nzb_segment_identity.json"
];

var VECTORS_DIR = path.join(__dirname, "test-vectors");

function loadFixture(name) {
    return JSON.parse(fs.readFileSync(path.join(VECTORS_DIR, name), "utf8"));
}

function sha256(file) {
    return crypto.createHash("sha256")
        .update(fs.readFileSync(path.join(VECTORS_DIR, file)))
        .digest("hex");
}

function testManifestSha256Sync() {
    var manifest = loadFixture("manifest.json");
    assert.strictEqual(manifest.standard_version, "1.2", "fixture set must be v1.2");
    assert.deepStrictEqual(
        Object.keys(manifest.files).sort(),
        VECTOR_FILES.slice().sort(),
        "manifest must list exactly the canonical 7 vector files"
    );
    VECTOR_FILES.forEach(function(file) {
        var expected = manifest.files[file].sha256;
        assert.ok(expected, "manifest entry missing sha256 for " + file);
        assert.strictEqual(sha256(file), expected, "sha256 drift for " + file);
    });
}

function testVec01Argon2id() {
    var vectors = loadFixture("argon2id.json").vectors;
    assert.strictEqual(vectors.length, 6, "VEC-01 set has 6 vectors");

    vectors.forEach(function(v) {
        var salt = Buffer.from(v.salt_hex, "hex");
        var derivedKey = encryption.deriveMasterKey(v.password, salt);
        assert.strictEqual(
            derivedKey.toString("hex"),
            v.expected_key_hex,
            v.id + ": Argon2id derived key mismatch"
        );
    });
}

function testVec02NonceTweak() {
    var fixture = loadFixture("nonce_tweak.json");
    var bodyNonceVectors = fixture.body_nonce_vectors;
    var controlTweakVectors = fixture.control_tweak_vectors;

    assert.strictEqual(bodyNonceVectors.length, 8, "VEC-02 body nonce set has 8 vectors");
    assert.strictEqual(controlTweakVectors.length, 7, "VEC-02 control tweak set has 7 vectors");

    bodyNonceVectors.forEach(function(v) {
        var key = Buffer.from(v.key_hex, "hex");
        var nonce = encryption.deriveBodyNonce(key, v.segment_index);
        assert.strictEqual(
            nonce.toString("hex"),
            v.expected_nonce_hex,
            v.id + ": body nonce mismatch"
        );
    });

    controlTweakVectors.forEach(function(v) {
        var masterKey = Buffer.from(v.master_key_hex, "hex");
        var encKey = encryption.deriveControlEncKey(masterKey);
        assert.strictEqual(
            encKey.toString("hex"),
            v.enc_key_hex,
            v.id + ": control enc key mismatch"
        );

        var tweak = encryption.deriveControlTweak(masterKey, v.segment_index, v.line_index);
        assert.strictEqual(
            tweak.toString("hex"),
            v.expected_tweak_hex,
            v.id + ": control tweak mismatch"
        );
    });
}

function testVec03BodyEncryption() {
    var vectors = loadFixture("body_encryption.json").vectors;
    assert.strictEqual(vectors.length, 8, "VEC-03 set has 8 vectors");

    vectors.forEach(function(v) {
        var masterKey = Buffer.from(v.derived_key_hex, "hex");
        var salt = Buffer.from(v.salt_hex, "hex");
        var plaintext = Buffer.from(v.plaintext_hex, "hex");

        // 1. Encrypt body
        var result = encryption.encryptBody(masterKey, v.segment_index, plaintext);
        assert.strictEqual(
            result.ciphertext.toString("hex"),
            v.expected_ciphertext_hex,
            v.id + ": ciphertext mismatch"
        );
        assert.strictEqual(
            result.tag.toString("hex"),
            v.expected_tag_hex,
            v.id + ": authentication tag mismatch"
        );

        // 2. Build canonical =yencryption line
        var yencLine = encryption.buildYencryptionLine(salt, v.segment_index, result.tag);
        assert.strictEqual(
            yencLine,
            v.expected_yencryption_line,
            v.id + ": =yencryption line mismatch"
        );
        assert.strictEqual(yencLine.length, 128, v.id + ": =yencryption line must be 128 chars");

        // 3. Parse canonical line
        var parsed = encryption.parseYencryptionLine(yencLine);
        assert.strictEqual(parsed.cipher, "XChaCha20-Poly1305", v.id + ": parsed cipher");
        assert.strictEqual(parsed.salt.toString("hex"), v.salt_hex, v.id + ": parsed salt");
        assert.strictEqual(parsed.segmentIndex, v.segment_index, v.id + ": parsed index");
        assert.strictEqual(parsed.tag.toString("hex"), v.expected_tag_hex, v.id + ": parsed tag");

        // 4. Decrypt body and verify bit-for-bit plaintext match
        var decrypted = encryption.decryptBody(masterKey, v.segment_index, result.ciphertext, result.tag);
        assert.strictEqual(
            decrypted.toString("hex"),
            v.plaintext_hex,
            v.id + ": decrypted plaintext mismatch"
        );
    });
}

function testVec04ControlLineEncryption() {
    var vectors = loadFixture("control_line_encryption.json").vectors;
    assert.strictEqual(vectors.length, 8, "VEC-04 set has 8 vectors");

    vectors.forEach(function(v) {
        var masterKey = encryption.deriveMasterKey(v.password, Buffer.from(v.salt_hex, "hex"));
        var encKey = encryption.deriveControlEncKey(masterKey);

        if (v.is_line_1) {
            // Line 1 with bootstrap prefix
            var salt = Buffer.from(v.salt_hex, "hex");
            var wire = encryption.encryptLine1(encKey, masterKey, v.segment_index, salt, Buffer.from(v.plaintext_line, "ascii"));
            assert.strictEqual(
                wire.toString("hex"),
                v.expected_wire_hex,
                v.id + ": line 1 wire hex mismatch"
            );
            assert.strictEqual(wire.length, v.expected_wire_length, v.id + ": wire length");

            // Decrypt Line 1
            var dec1 = encryption.decryptLine1(encKey, masterKey, wire);
            assert.strictEqual(dec1.salt.toString("hex"), v.salt_hex, v.id + ": decrypted salt");
            assert.strictEqual(dec1.segmentIndex, v.segment_index, v.id + ": decrypted segmentIndex");
            assert.strictEqual(dec1.plaintextLine.toString("ascii"), v.plaintext_line, v.id + ": decrypted plaintext line");
        } else if (v.plaintext_line) {
            // Individual control lines (lines 2, 3, 4, 54)
            var tweak = encryption.deriveControlTweak(masterKey, v.segment_index, v.line_index);
            var wireLine = encryption.ff1EncryptLine(encKey, tweak, Buffer.from(v.plaintext_line, "ascii"));
            assert.strictEqual(
                wireLine.toString("hex"),
                v.expected_wire_hex,
                v.id + ": control line wire hex mismatch"
            );
            assert.strictEqual(wireLine.length, v.expected_wire_length, v.id + ": exact length preservation");

            // Decrypt control line
            var decLine = encryption.ff1DecryptLine(encKey, tweak, wireLine);
            assert.strictEqual(
                decLine.toString("ascii"),
                v.plaintext_line,
                v.id + ": decrypted control line mismatch"
            );
        } else if (v.input_lines) {
            // Full article multi-line test vectors (4 lines and 54 lines)
            var session = {
                masterKey: masterKey,
                controlEncKey: encKey,
                salt: Buffer.from(v.salt_hex, "hex")
            };
            var articleInput = Buffer.from(v.input_lines.join("\r\n") + "\r\n", "ascii");
            var encryptedArticle = encryption.encryptControlLines(session, v.segment_index, articleInput);

            // Split encrypted article and check line-by-line wire hex
            var lines = [];
            var start = 0;
            for (var i = 0; i < encryptedArticle.length; i++) {
                if (encryptedArticle[i] === 0x0a) {
                    var line = encryptedArticle.subarray(start, i + 1);
                    if (line.length >= 2 && line[line.length - 2] === 0x0d) {
                        line = line.subarray(0, line.length - 2);
                    } else {
                        line = line.subarray(0, line.length - 1);
                    }
                    lines.push(line);
                    start = i + 1;
                }
            }

            assert.strictEqual(lines.length, v.total_physical_lines, v.id + ": physical line count");
            for (var lIdx = 0; lIdx < lines.length; lIdx++) {
                assert.strictEqual(
                    lines[lIdx].toString("hex"),
                    v.expected_wire_lines_hex[lIdx],
                    v.id + " line " + (lIdx + 1) + " wire hex mismatch"
                );
            }

            // Decrypt full article and check bit-for-bit reconstruction
            var decryptedArt = encryption.decryptControlLines(masterKey, encryptedArticle);
            assert.strictEqual(decryptedArt.salt.toString("hex"), v.salt_hex, v.id + ": article salt");
            assert.strictEqual(decryptedArt.segmentIndex, v.segment_index, v.id + ": article segmentIndex");
            assert.strictEqual(
                decryptedArt.buffer.toString("ascii"),
                articleInput.toString("ascii"),
                v.id + ": full article round-trip mismatch"
            );
        }
    });
}

function testMalformedRejectionShapes() {
    var vectors = loadFixture("malformed_inputs.json").vectors;
    assert.strictEqual(vectors.length, 46, "v1.2 malformed set has 46 vectors");

    vectors.forEach(function(v) {
        assert.ok(v.expected_error, v.id + ": expected_error");
        assert.ok(
            v.expected_rejection_stage === "PROVIDER_FAILOVER" ||
            v.expected_rejection_stage === "METADATA_VALIDATION",
            v.id + ": unexpected rejection stage " + v.expected_rejection_stage
        );
        assert.strictEqual(v.zero_output_required, true, v.id + ": zero-output guarantee");
    });

    // Authentication failures must stay retryable: eligible for provider
    // failover and never released as final output.
    var authFailures = vectors.filter(function(v) { return v.expected_error === "AUTHENTICATION_FAILURE"; });
    assert.strictEqual(authFailures.length, 4, "4 auth-failure vectors");
    authFailures.forEach(function(v) {
        assert.strictEqual(v.expected_rejection_stage, "PROVIDER_FAILOVER", v.id);
        assert.strictEqual(v.provider_failover_permitted, true, v.id);

        // Execute cryptographic negative assertion
        var salt = Buffer.from(v.salt_hex, "hex");
        var masterKey = encryption.deriveMasterKey(v.password, salt);
        var ct = Buffer.from(v.tampered_ciphertext_hex || v.ciphertext_hex, "hex");
        var tag = Buffer.from(v.tampered_tag_hex || v.tag_hex, "hex");

        assert.throws(function() {
            encryption.decryptBody(masterKey, v.segment_index, ct, tag);
        }, function(err) {
            return err && (err.message === "AUTHENTICATION_FAILURE" || err.code === "AUTHENTICATION_FAILURE");
        }, v.id + ": decryptBody must throw AUTHENTICATION_FAILURE");
    });

    // Metadata-shape failures are job-level, never provider corruption.
    var metadataFailures = vectors.filter(function(v) { return v.expected_rejection_stage === "METADATA_VALIDATION"; });
    assert.strictEqual(metadataFailures.length, 4, "4 metadata-validation vectors");
    metadataFailures.forEach(function(v) {
        assert.strictEqual(v.provider_failover_permitted, false, v.id);
    });

    // header_syntax vectors carry a full =yencryption line to reject
    vectors.filter(function(v) { return v.category === "header_syntax"; }).forEach(function(v) {
        var line = v.input_line || "";
        assert.ok(
            line.indexOf("=yencryption") === 0 &&
            line.length > "=yencryption".length &&
            !/[a-zA-Z0-9]/.test(line.charAt("=yencryption".length)),
            v.id + ": header_syntax vector missing input_line"
        );

        assert.throws(function() {
            encryption.parseYencryptionLine(line);
        }, function(err) {
            return err && err.message === v.expected_error;
        }, v.id + ": parseYencryptionLine must throw " + v.expected_error);
    });

    // FORBIDDEN_SEGMENT_INDEX_BYTE control-syntax vectors: bootstrap line is
    // 22 bytes with the segmentIndex in the 4 big-endian bytes at offset 16.
    vectors.filter(function(v) { return v.expected_error === "FORBIDDEN_SEGMENT_INDEX_BYTE"; }).forEach(function(v) {
        assert.ok(v.line1_hex, v.id + ": line1_hex");
        var line1 = Buffer.from(v.line1_hex, "hex");
        assert.strictEqual(line1.length, 22, v.id + ": bootstrap line must be 22 bytes");
        var index = line1.readUInt32BE(16);
        assert.ok(indexForbidden(index), v.id + ": index " + index + " should be forbidden");

        var dummyKey = Buffer.alloc(32, 1);
        assert.throws(function() {
            encryption.decryptLine1(dummyKey, dummyKey, line1);
        }, function(err) {
            return err && err.message === "FORBIDDEN_SEGMENT_INDEX_BYTE";
        }, v.id + ": decryptLine1 must throw FORBIDDEN_SEGMENT_INDEX_BYTE");
    });
}

function testNzbMetaTagExpectations() {
    var vectors = loadFixture("nzb_segment_identity.json").vectors;
    assert.strictEqual(vectors.length, 33, "VEC-06 set has 33 vectors");

    var encrypted = vectors.filter(function(v) { return v.is_encrypted; });
    var unencrypted = vectors.filter(function(v) { return v.is_encrypted === false; });
    assert.ok(encrypted.length > 0, "fixture contains encrypted vectors");
    assert.strictEqual(unencrypted.length, 2, "two unencrypted reference vectors");

    encrypted.forEach(function(v) {
        assert.ok(v.nzb_xml.indexOf('<meta type="yenc_encrypted">true</meta>') !== -1, v.id);
        assert.ok(v.nzb_xml.indexOf('<meta type="password">') !== -1, v.id);
    });

    unencrypted.forEach(function(v) {
        assert.ok(v.nzb_xml.indexOf('<meta type="yenc_encrypted">') === -1, v.id);
        assert.ok(v.nzb_xml.indexOf('<meta type="password">') === -1, v.id);
        assert.strictEqual(v.expected_valid, true, v.id);
        v.expected_segments.forEach(function(segment) {
            assert.strictEqual(segment.segment_index, null, v.id);
        });
    });
}

// VEC-07: a candidate segmentIndex whose uint32 big-endian encoding contains
// 0x0A or 0x0D is forbidden; the uploader must skip forward to the next
// permitted index.
function indexForbidden(index) {
    var be = Buffer.alloc(4);
    be.writeUInt32BE(index >>> 0, 0);
    return be.includes(0x0a) || be.includes(0x0d);
}

function nextPermitted(candidate) {
    var i = candidate >>> 0;
    while (indexForbidden(i)) {
        i = (i + 1) >>> 0;
    }
    return i;
}

function testIndexAllocationSkipRules() {
    var vectors = loadFixture("index_allocation.json").vectors;
    assert.strictEqual(vectors.length, 4, "canonical VEC-07 set has 4 vectors");

    vectors.forEach(function(v) {
        var assigned = v.expected_assigned_index;
        // By design (vector 04): candidate 269 is itself forbidden - the
        // uploader must never assign it - so only the assigned index is
        // required to be permitted.
        assert.ok(!indexForbidden(assigned), v.id + ": assigned index must be permitted");
        assert.strictEqual(nextPermitted(v.candidate_index), assigned, v.id);
        assert.strictEqual(encryption.nextPermittedIndex(v.candidate_index), assigned, v.id);
        var be = Buffer.alloc(4);
        be.writeUInt32BE(assigned >>> 0, 0);
        assert.strictEqual(be.toString("hex"), v.expected_index_hex, v.id);
    });

    // Test SegmentIndexAllocator class
    var alloc = new encryption.SegmentIndexAllocator(10);
    assert.strictEqual(alloc.next(), 11);
    assert.strictEqual(alloc.next(), 12);
    assert.strictEqual(alloc.next(), 14); // 13 is skipped!
}

function testIndexAllocationReferenceSequence() {
    var vectors = loadFixture("index_allocation.json").vectors;
    var byId = {};
    vectors.forEach(function(v) { byId[v.id] = v; });
    assert.strictEqual(byId["index-allocation-01-skip-10"].expected_assigned_index, 11);
    assert.strictEqual(byId["index-allocation-02-skip-13"].expected_assigned_index, 14);
    assert.strictEqual(byId["index-allocation-03-skip-266"].expected_assigned_index, 267);
    assert.strictEqual(byId["index-allocation-04-skip-269"].expected_assigned_index, 270);
}

// Exported for the standalone runner below.
var TESTS = [
    testManifestSha256Sync,
    testVec01Argon2id,
    testVec02NonceTweak,
    testVec03BodyEncryption,
    testVec04ControlLineEncryption,
    testMalformedRejectionShapes,
    testNzbMetaTagExpectations,
    testIndexAllocationSkipRules,
    testIndexAllocationReferenceSequence
];

// Mocha registration (mocha injects describe/it as globals).
if (typeof global.describe === "function" && typeof global.it === "function") {
    describe("yEnc encryption standards v1.2 conformance fixtures", function() {
        this.timeout(60000);
        it("vendors all 7 vector files byte-identical to manifest.json sha256", testManifestSha256Sync);
        it("VEC-01 Argon2id master key derivation matches reference outputs", testVec01Argon2id);
        it("VEC-02 HMAC-SHA256 body nonce and control tweak derivations match reference outputs", testVec02NonceTweak);
        it("VEC-03 XChaCha20-Poly1305 body encryption & canonical header building match reference outputs", testVec03BodyEncryption);
        it("VEC-04 Radix-253 FF1 control-line encryption & bootstrap match reference outputs", testVec04ControlLineEncryption);
        it("VEC-05 malformed inputs pin error class, rejection stage and zero-output", testMalformedRejectionShapes);
        it("VEC-06 encrypted NZBs carry yenc_encrypted + password meta, plain NZBs do not", testNzbMetaTagExpectations);
        it("VEC-07 segmentIndex allocation skips 0x0A/0x0D candidates", testIndexAllocationSkipRules);
        it("VEC-07 canonical skip examples keep stable expected assignments", testIndexAllocationReferenceSequence);
    });
}

// Standalone runner: `node test/test_conformance_vectors.js`.
if (require.main === module) {
    var failures = 0;
    TESTS.forEach(function(t) {
        try {
            t();
            console.log("ok - " + t.name);
        } catch (err) {
            failures++;
            console.error("not ok - " + t.name + ": " + (err && err.message ? err.message : err));
        }
    });
    if (failures) {
        process.exit(1);
    }
    console.log("conformance vectors: all " + TESTS.length + " tests passed");
}
